spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 5

server:
  port: 8888
  servlet:
    context-path: /exec

jdbc:
  datasource:
    driverClass: com.mysql.cj.jdbc.Driver
    user: root
    password: root
    jdbcUrl: jdbc:mysql://localhost:3306/msgdb
    maxPoolSize: 100
    minPoolSize: 10
    initialPoolSize: 10